@CoalMineApi_HostAddress = http://localhost:5096

GET {{CoalMineApi_HostAddress}}/emissions/data
Accept: application/json

###

GET {{CoalMineApi_HostAddress}}/emissions/layer
Accept: application/json
###

GET {{CoalMineApi_HostAddress}}/coverages/data
Accept: application/json

###

GET {{CoalMineApi_HostAddress}}/coverages/layer
Accept: application/json
###

POST {{CoalMineApi_HostAddress}}/coverages/data
###