@CoalMineApi_HostAddress = http://localhost:5000

GET {{CoalMineApi_HostAddress}}/emissions/data

GET {{CoalMineApi_HostAddress}}/emissions/layer

POST {{CoalMineApi_HostAddress}}/emissions/data
Content-Type: application/json

{
  "CH4": 1.1,
  "C2H6": 2.2,
  "TimeStamp": "2023-10-01T12:00:00Z",
  "Longitude": -104.05,
  "Latitude": 48.99
}

GET {{CoalMineApi_HostAddress}}/coverages/data

POST {{CoalMineApi_HostAddress}}/coverages/data
Content-Type: application/json

{
  "Name": "Test Coverage",
  "Description": "Test Description",
  "BufferSize": 10,
  "Feature": "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-104.05,48.99],[-97.22,48.98],[-96.58,45.94],[-104.03,45.94],[-104.05,48.99]]]},\"properties\":{}}"
}

GET {{CoalMineApi_HostAddress}}/coverages/data/bulk

POST {{CoalMineApi_HostAddress}}/coverages/data/bulk
Content-Type: application/json

{
  "Name": "Test MultiPolygon Coverage",
  "Description": "Test Description",
  "BufferSize": 10,
  "FeatureCollection": "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-104.05,48.99],[-97.22,48.98],[-96.58,45.94],[-104.03,45.94],[-104.05,48.99]]]},\"properties\":{}},{\"type\":\"Feature\",\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-100.05,40.99],[-90.22,40.98],[-90.58,35.94],[-100.03,35.94],[-100.05,40.99]]]},\"properties\":{}}]}"
}