volumes:
  db-data:

services:
  postgis:
    image: kartoza/postgis:16
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=emissions
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD pg_isready -h 127.0.0.1 -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "5000:8080"
      depends_on:
        postgis:
          condition: service_healthy
      volumes:
        - ./appsettings.json:/app/appsettings.json
      restart: on-failure